title = "redisgo_task"

[redis]
#expire-锁默认expire「单位s」
#cron 持续增加expire频次
#retries_count 持续获取锁重试次数，重试间隔遵循退避算法，于次数耦合
#monitor_try_all 标识是否永久重试抢锁，true/false
host = "IP:HOST"
key = "Redisgo_Task_Lock_key"
monitor_try_all = true
#retries_count = 4.0
# value = "8292884c-a7a7-0050-9778-e47362a8f578"
# expire = "5s"
# cron = "1s"
